apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-private
  namespace: ingress-nginx-private
data:
  ingress-nginx-values: |
    ingress-nginx:
      fullnameOverride: "ingress-nginx-private"
      controller:
        ingressClass: "ingress-nginx-private"
        ingressClassResource:
          name: "nginx-private"
          controllerValue: "k8s.io/ingress-nginx-private"
        service:
          external:
            enabled: false
          internal:
            enabled: true
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-name: "ingress-nginx-private-lb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-public
  namespace: ingress-nginx-public
data:
  ingress-nginx-values: |
    ingress-nginx:
      fullnameOverride: "ingress-nginx-public"
      controller:
        ingressClass: "ingress-nginx-public"
        ingressClassResource:
          name: "nginx-public"
          controllerValue: "k8s.io/ingress-nginx-public"
        service:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-name: "ingress-nginx-public-lb"
          external:
            enabled: true
          internal:
            enabled: false
