apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: cms
    app.kubernetes.io/part-of: openedx
  name: cms
  namespace: openedx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: cms
      app.kubernetes.io/part-of: openedx
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: cms
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - env:
            - name: SERVICE_VARIANT
              value: cms
            - name: DJANGO_SETTINGS_MODULE
              value: cms.envs.tutor.production
            - name: UWSGI_WORKERS
              value: "2"
          image: docker.io/overhangio/openedx:21.0.0
          name: cms
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /openedx/edx-platform/lms/envs/tutor/
              name: settings-lms
            - mountPath: /openedx/edx-platform/cms/envs/tutor/
              name: settings-cms
            - mountPath: /openedx/config
              name: config
            - mountPath: /openedx/uwsgi.ini
              name: uwsgi-config
              subPath: uwsgi.ini
          envFrom:
            - secretRef:
                name: openedx-secrets
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: openedx-service-account
      volumes:
        - configMap:
            name: openedx-settings-lms
          name: settings-lms
        - configMap:
            name: openedx-settings-cms
          name: settings-cms
        - configMap:
            name: openedx-config
          name: config
        - configMap:
            items:
              - key: uwsgi.ini
                path: uwsgi.ini
            name: openedx-uwsgi-config
          name: uwsgi-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: cms-worker
    app.kubernetes.io/part-of: openedx
  name: cms-worker
  namespace: openedx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: cms-worker
      app.kubernetes.io/part-of: openedx
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: cms-worker
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - args:
            - celery
            - --app=cms.celery
            - worker
            - --loglevel=info
            - --hostname=edx.cms.core.default.%h
            - --queues=edx.cms.core.default,edx.cms.core.high,edx.cms.core.low
            - --max-tasks-per-child=100
            - --prefetch=1
            - --without-gossip
            - --without-mingle
          env:
            - name: SERVICE_VARIANT
              value: cms
            - name: DJANGO_SETTINGS_MODULE
              value: cms.envs.tutor.production
          image: docker.io/overhangio/openedx:21.0.0
          name: cms-worker
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /openedx/edx-platform/lms/envs/tutor/
              name: settings-lms
            - mountPath: /openedx/edx-platform/cms/envs/tutor/
              name: settings-cms
            - mountPath: /openedx/config
              name: config
          envFrom:
            - secretRef:
                name: openedx-secrets
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: openedx-service-account
      volumes:
        - configMap:
            name: openedx-settings-lms
          name: settings-lms
        - configMap:
            name: openedx-settings-cms
          name: settings-cms
        - configMap:
            name: openedx-config
          name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: lms
    app.kubernetes.io/part-of: openedx
  name: lms
  namespace: openedx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: lms
      app.kubernetes.io/part-of: openedx
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: lms
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - env:
            - name: SERVICE_VARIANT
              value: lms
            - name: DJANGO_SETTINGS_MODULE
              value: lms.envs.tutor.production
            - name: UWSGI_WORKERS
              value: "2"
          image: docker.io/overhangio/openedx:21.0.0
          name: lms
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /openedx/edx-platform/lms/envs/tutor/
              name: settings-lms
            - mountPath: /openedx/edx-platform/cms/envs/tutor/
              name: settings-cms
            - mountPath: /openedx/config
              name: config
            - mountPath: /openedx/uwsgi.ini
              name: uwsgi-config
              subPath: uwsgi.ini
          envFrom:
            - secretRef:
                name: openedx-secrets
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: openedx-service-account
      volumes:
        - configMap:
            name: openedx-settings-lms
          name: settings-lms
        - configMap:
            name: openedx-settings-cms
          name: settings-cms
        - configMap:
            name: openedx-config
          name: config
        - configMap:
            items:
              - key: uwsgi.ini
                path: uwsgi.ini
            name: openedx-uwsgi-config
          name: uwsgi-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: lms-worker
    app.kubernetes.io/part-of: openedx
  name: lms-worker
  namespace: openedx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: lms-worker
      app.kubernetes.io/part-of: openedx
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: lms-worker
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - args:
            - celery
            - --app=lms.celery
            - worker
            - --loglevel=info
            - --hostname=edx.lms.core.default.%h
            - --queues=edx.lms.core.default,edx.lms.core.high,edx.lms.core.high_mem
            - --max-tasks-per-child=100
            - --prefetch=1
            - --without-gossip
            - --without-mingle
          env:
            - name: SERVICE_VARIANT
              value: lms
            - name: DJANGO_SETTINGS_MODULE
              value: lms.envs.tutor.production
          image: docker.io/overhangio/openedx:21.0.0
          name: lms-worker
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /openedx/edx-platform/lms/envs/tutor/
              name: settings-lms
            - mountPath: /openedx/edx-platform/cms/envs/tutor/
              name: settings-cms
            - mountPath: /openedx/config
              name: config
          envFrom:
            - secretRef:
                name: openedx-secrets
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: openedx-service-account
      volumes:
        - configMap:
            name: openedx-settings-lms
          name: settings-lms
        - configMap:
            name: openedx-settings-cms
          name: settings-cms
        - configMap:
            name: openedx-config
          name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/part-of: openedx
  name: meilisearch
  namespace: openedx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: meilisearch
      app.kubernetes.io/part-of: openedx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: meilisearch
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - env:
            - name: MEILI_MASTER_KEY
              value: 9oXNCjn2dEQxfUhdygpQaYz8
          image: docker.io/getmeili/meilisearch:v1.8.4
          name: meilisearch
          ports:
            - containerPort: 7700
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /meili_data
              name: data
          envFrom:
            - secretRef:
                name: openedx-secrets
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: meilisearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: mfe
    app.kubernetes.io/part-of: openedx
  name: mfe
  namespace: openedx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: mfe
      app.kubernetes.io/part-of: openedx
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: mfe
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - image: docker.io/overhangio/openedx-mfe:21.0.0
          name: mfe
          ports:
            - containerPort: 8002
          volumeMounts:
            - mountPath: /etc/caddy/
              name: config
          envFrom:
            - secretRef:
                name: openedx-secrets
      volumes:
        - configMap:
            name: mfe-caddy-config
          name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/name: smtp
    app.kubernetes.io/part-of: openedx
  name: smtp
  namespace: openedx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
      app.kubernetes.io/managed-by: tutor
      app.kubernetes.io/name: smtp
      app.kubernetes.io/part-of: openedx
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/name: smtp
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - image: docker.io/devture/exim-relay:4.96-r1-0
          name: smtp
          ports:
            - containerPort: 8025
          envFrom:
            - secretRef:
                name: openedx-secrets
      securityContext:
        runAsGroup: 101
        runAsUser: 100
