apiVersion: v1
kind: Service
metadata:
  name: cms
  labels:
    app.kubernetes.io/name: cms
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: cms
---
apiVersion: v1
kind: Service
metadata:
  name: lms
  labels:
    app.kubernetes.io/name: lms
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: lms
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  labels:
    app.kubernetes.io/name: meilisearch
spec:
  type: ClusterIP
  ports:
    - port: 7700
      protocol: TCP
  selector:
    app.kubernetes.io/name: meilisearch
---
apiVersion: v1
kind: Service
metadata:
  name: smtp
  labels:
    app.kubernetes.io/name: smtp
spec:
  type: ClusterIP
  ports:
    - port: 8025
      protocol: TCP
  selector:
    app.kubernetes.io/name: smtp
---
apiVersion: v1
kind: Service
metadata:
  name: mfe
spec:
  type: ClusterIP
  ports:
    - port: 8002
      protocol: TCP
  selector:
    app.kubernetes.io/name: mfe
